#conda env create --prefix ./macro_variables_env --file ./config/macro_variables_env.yml
name: macro_variables_env
dependencies:
  - plotly
  - pandas
  - numpy
  - matplotlib
  - openpyxl
  - pip
  - pip:
    - kaleido

#if you want to use the #%% things that finn uses then install jupyter and ipykernel using conda as well.